### ISSUE TITLE
No such file or directory - connect(2) for /tmp/mysql.sock

### ISSUE THREAD

**Issue by 030** [sensu-plugins/sensu-plugins-mysql#24]
Running `/opt/sensu/embedded/bin/check-mysql-connections.rb` on Ubuntu Xenial results in:

```
Check failed to run: No such file or directory - connect(2) for /tmp/mysql.sock, 
["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql/protocol.rb:150:in
 `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql
/protocol.rb:150:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql
/protocol.rb:150:in `block in initialize'", "/opt/sensu/embedded/lib/ruby/2.3.0/timeout.rb:74:in `timeout'", 
"/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql/protocol.rb:147:in 
`initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql.rb:115:in 
`new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql.rb:115:in 
`connect'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ruby-mysql-2.9.14/lib/mysql.rb:50:in 
`new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-mysql-1.0.0/bin/check-mysql-
connections.rb:79:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

while the database is running:
- port 3306 is listening
- `mysql` opens a console and issuing `show databases` shows the databases

**Comment by eheydrick** [comment]
The problem is it's always trying to connect via socket and ruby-mysql defaults to /tmp/mysql.sock. I think the check needs to be reworked to connect via tcp by default and socket if specified. Here's a workaround until that happens: `check-mysql-connections.rb -s /var/run/mysqld/mysqld.sock ...`

**Comment by MrMoronIV** [comment]
I don't have a socket since it's a remote database, how do I force it to use TCP instead to login?
